import { useAnchorWallet, useConnection } from '@solana/wallet-adapter-react'
import { AnchorProvider, Program } from '@coral-xyz/anchor'
import { PublicKey } from '@solana/web3.js'
// Bundled copy of Anchor IDL — refresh from `target/idl/medovant.json` after `anchor build`.
import idl from '../idl/medovant.json'

const PROGRAM_ID = new PublicKey('5JMd8ADy1KHBhohX6NLbz6WQdyCQTfLd55Gmzo2r34WD')

/**
 * Anchor Program instance bound to the connected wallet.
 * IDL is generated by `anchor build` at repo root — keep path in sync.
 */
export function useProgram() {
  const wallet = useAnchorWallet()
  const { connection } = useConnection()
  if (!wallet) return { program: null, provider: null, programId: PROGRAM_ID }
  const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new Program(idl as never, provider)
  return { program, provider, programId: PROGRAM_ID }
}
